CREATE TABLE [dbo].[T_Unit]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] UNIQUEIDENTIFIER NULL, 
    [Cost] INT NULL, 
    [Fluff] NVARCHAR(MAX) NULL, 
    [Source] UNIQUEIDENTIFIER NULL, 
    [Source_Page] INT NULL
)
