CREATE TABLE [dbo].[T_Unit]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(MAX) NULL, 
    [Cost] INT NULL, 
    [Role] NVARCHAR(25) NULL,
    [Fluff] NVARCHAR(MAX) NULL, 
    [Source] UNIQUEIDENTIFIER NULL, 
    [Source_Page] INT NULL
)
