CREATE TABLE [dbo].[T_Wargear]
(
	[Id] UNIQUEIDENTIFIER NOT NULL, 
    [Name] NVARCHAR(50) NULL, 
    [Fluff] NVARCHAR(MAX) NULL, 
    [Rules] NVARCHAR(MAX) NULL,
    [Row_Id] INT IDENTITY(1,1) NOT NULL,
    CONSTRAINT [PK_T_Wargear_Id] PRIMARY KEY NONCLUSTERED ([Id])
)

GO

CREATE UNIQUE INDEX [CIX_T_Wargear_Column] ON [dbo].[T_Wargear] ([ROW_ID])
